<?php
use Elgentos\PrismicIO\Block\Template;
use Magento\Framework\Escaper;

/**
 * @var Template $block
 * @var Escaper $escaper
 */

$icon = $escaper->escapeHtml($block->getChildHtml('icon'));
$text = $escaper->escapeHtml($block->getChildHtml('text'));
?>

<div class="col-md-4">
    <div class="usps__description">
        <svg class="icon icons__item" role="img">
            <title><?= $text; ?></title>
            <use xlink:href="<?= $escaper->escapeUrl($block->getViewFileUrl('/images/icons-sprite.svg')); ?>#<?= $icon; ?>"></use>
        </svg>
        <?= $text; ?>
    </div>
</div>
