<?php

declare(strict_types=1);

use Elgentos\PrismicIO\Block\Template;
use Magento\Framework\Escaper;

/** @var Template $block */
/** @var Escaper $escaper */

$dummy = $block->getContext();
$bg     = $block->getChildHtml('background_color');
$color  = $block->getChildHtml('text_color');
$style  = $block->getChildHtml('style');
$type   = $block->getChildHtml('type');
//var_dump($block->getContext());die; // show only output
//highlight_string(print_r($dummy, true)); // show inline on page
?>
<div class="width-full <?= ($style ? '' : 'container') ?>">
    <div class="row bg-<?= ($bg ?: 'transparent'); ?> <?= ($style ? 'rounded-5' : '') ?> items-start text-color-<?= $color; ?>">
        <?=/* @noEscape */  $block->getChildHtml('prismicio.header2.body'); ?>
    </div>
</div>
