<?php

declare(strict_types=1);

use Elgentos\PrismicIO\Block\Template;
use Magento\Framework\Escaper;

/** @var Template $block */
/** @var Escaper $escaper */

$dummy  = $block->getContext();

$bg     = $block->getChildHtml('background_color');
$color  = $block->getChildHtml('text_color');
$width  = str_replace('/12', '', $block->getChildHtml('width'));
$type   = $block->getChildHtml('type');
//var_dump($block->getContext());die; // show only output
//highlight_string(print_r($dummy, true)); // show inline on page

?>

<section class="bg-<?= ($bg ?: 'transparent'); ?> xs-col-12 md-col-<?= $width; ?> mb-l">
    <div class="flex">
        <?=/* @noEscape */  $block->getChildHtml($type) ?>
    </div>
</section>
