<?php declare(strict_types=1);

/**
 * @var $block Template
 * @var $escaper Escaper
 */

use Elgentos\PrismicIO\Block\Template;
use Magento\Framework\Escaper;

$day = $escaper->escapeHtmlAttr($block->getChildHtml('day'));
$time = $escaper->escapeHtmlAttr($block->getChildHtml('open_close'));
?>

<div class="flex flex--between">
    <span class="<?= strtolower($day); ?>"><?= $day; ?></span>
    <span><?= $time; ?></span>
</div>
