<?php declare(strict_types=1);

/**
 * @var $escaper Escaper
 * @var $block Template
 */

use Elgentos\PrismicIO\Block\Template;
use Magento\Framework\Escaper;

$gridColumn = $block->getChildHtml('grid');
$backgroundColor = $block->getChildHtml('background');
$badge = $block->getChildHtml('category_badge');
$type = $block->getChildHtml('type');

?>

<?php if ($gridColumn !== 'slider-item'): ?>
    <?php if ($type !== 'category_banner'): ?>
        <div class="col-xs-<?= ($escaper->escapeHtml($gridColumn)*2) ?> col-lg-<?= $escaper->escapeHtml($gridColumn) ?> mb-l <?= ($escaper->escapeHtml($badge) ? 'category-item--badged' : '')?>">
    <?php endif; ?>
<?php endif; ?>
    <?=/* @noEscape */  $block->getChildHtml($type) ?>
<?php if ($gridColumn !== 'slider-item'): ?>
    <?php if ($type !== 'category_banner'): ?>
        </div>
    <?php endif; ?>
<?php endif; ?>
