<?php declare(strict_types=1);

/**
 * @var $block Template
 * @var $escaper Escaper
 */

use Elgentos\PrismicIO\Block\Template;
use Magento\Framework\Escaper;

$width    = str_replace('/12', '', $block->getChildHtml('width'));

?>

<section class="footer__paymentlogos col-xs-12 col-md-<?= $width ?> mb-l">
    <ul class="list list--horizontal paymenticons__list paymenticons__footer--list justify-between">
        <?= /* @noEscape */ $block->getChildHtml('items'); ?>
    </ul>
</section>
