<?php declare(strict_types=1);

/**
 * @var $block Template
 * @var $escaper Escaper
 */

use Elgentos\PrismicIO\Block\Template;
use Magento\Framework\Escaper;

$context = $block->getContext();

$title      = $escaper->escapeHtml($block->getChildHtml('title'));
$link       = $escaper->escapeUrl($block->getChildHtml('link'));
?>
<li>
    <?php if ($link) : ?>
        <a href="<?= $link ?>" title="<?= $title ?>">
        <?php endif; ?>
        <?= $title ?>
    <?php if ($link) : ?>
        </a>
    <?php endif; ?>
</li>
