<?php declare(strict_types=1);

/**
 * @var $block Template
 * @var $escaper Escaper
 */

use Elgentos\PrismicIO\Block\Template;
use Magento\Framework\Escaper;

$context = $block->getContext();

$title      = $escaper->escapeHtml($block->getChildHtml('heading'));
$link       = $escaper->escapeUrl($block->getChildHtml('link'));

$width      = str_replace('/12', '', $block->getChildHtml('grid'));
$background = $escaper->escapeHtmlAttr($block->getChildHtml('background'));
?>

<section class="subcategory-list background-color--<?= $background; ?>  col-xs-12 col-md-<?= $width ?> column-gap-m mb-l">
    <h2>
        <?php if ($link) : ?>
            <a href="<?= $link ?>" title="<?= $title ?>">
        <?php endif; ?>
                <?= $title ?>
        <?php if ($link) : ?>
            </a>
        <?php endif; ?>
    </h2>

    <div class="flex flex-wrap justify-center">
        <?= /* @noEscape */ $block->getChildHtml('items'); ?>
    </div>
</section>
