<?php declare(strict_types=1);

/**
 * @var $block Template
 * @var $escaper Escaper
 */

use Elgentos\PrismicIO\Block\Template;
use Magento\Framework\Escaper;

$type = $block->getChildHtml('type');
$link = $escaper->escapeUrl($block->getChildHtml('url'));

?>

<div class="row">
    <a href="<?= $link; ?>" class="action-block t-d--n width-full">
    <?= $block->getChildHtml($type) ?>
    </a>
</div>
