<?php declare(strict_types=1);

/**
 * @var $block Template
 * @var $escaper Escaper
 */

use Elgentos\PrismicIO\Block\Template;
use Magento\Framework\Escaper;

$color      = $escaper->escapeHtmlAttr($block->getChildHtml('color'));
$geLink     = $escaper->escapeUrl($block->getChildHtml('link'));
$getLabel   = $escaper->escapeHtmlAttr($block->getChildHtml('label'));

?>
<span class="color--<?= $color; ?> footer__absolute-footer__item">
    <?php if($geLink): ?>
        <a href="<?= $geLink; ?>" title="<?= $getLabel; ?>" class="color--<?= $color; ?>">
    <?php endif; ?>

            <?= $getLabel; ?>

    <?php if($geLink): ?>
        </a>
    <?php endif; ?>
</span>
