<?php declare(strict_types=1);

/**
 * @var $block Template
 * @var $escaper Escaper
 */

use Elgentos\PrismicIO\Block\Template;
use Magento\Framework\Escaper;

$color = $escaper->escapeHtmlAttr($block->getChildHtml('color'));
$url   = $escaper->escapeUrl($block->getChildHtml('link'));
$label = $escaper->escapeHtmlAttr($block->getChildHtml('label'));

?>
<span class="footer__absolute-footer__item color-<?= $color; ?> text-<?= $color; ?>">
    <?php if($url): ?>
        <a href="<?= $url; ?>" title="<?= $label; ?>" class="text-<?= $color; ?>">
    <?php endif; ?>

            <?= $label; ?>

    <?php if($url): ?>
        </a>
    <?php endif; ?>
</span>
