<?php declare(strict_types=1);

/**
 * @var $block Template
 * @var $escaper Escaper
 */

use Elgentos\PrismicIO\Block\Template;
use Magento\Framework\Escaper;

$width      = str_replace('/12', '', $block->getChildHtml('width'));
$background = $escaper->escapeHtmlAttr($block->getChildHtml('background'));
?>

<section class="footer__absolute-footer background-color--<?= $background; ?>  col-xs-12 col-md-<?= $width ?> column-gap-m mb-l">
    <?= /* @noEscape */ $block->getChildHtml('items'); ?>
</section>
