<?php declare(strict_types=1);

/**
 * @var $block Template
 * @var $escaper Escaper
 */

use Elgentos\PrismicIO\Block\Template;
use Magento\Framework\Escaper;

$heading  = $escaper->escapeHtml($block->getChildHtml('heading'));
$sliderId = $escaper->escapeHtml(uniqid());
?>

<section class="header__socials mb-l">
    <div class="container">
        <div class="flex flex-direction-column">
            <h3 class="font-size--l p-t--4 p-b--1 text-center font-weight--600"><?= $heading ?></h3>

            <div class="sliderhtml-<?= $sliderId; ?>">
                <?=/* @noEscape */ $block->getChildHtml('items') ?>
            </div>
        </div>
    </div>
</section>
