<?php declare(strict_types=1);

/**
 * @var $block Template
 * @var $escaper Escaper
 *
 */

use Elgentos\PrismicIO\Block\Template;
use Magento\Framework\Escaper;

$width    = str_replace('/12', '', $block->getChildHtml('width'));
$bg       = $block->getChildHtml('background_color');

?>

<section class="contact-bar__footer span-item-12 lg:span-item-<?= $width; ?> mb-4 bg-<?= ($bg ?: 'transparent'); ?>  p-4 mt-0">
    <h3 class="heading--third-level"><?= $block->getChildHtml('heading'); ?></h3>
    <div class="row">
        <?=/* @noEscape */ $block->getChildHtml('items') ?>
    </div>
</section>
