<?php

//declare(strict_types=1);

/**
 * @var $block Template
 * @var $escaper Escaper
 * @var $viewModel StoreInfo
 */
use Elgentos\PrismicIO\Block\Template;
use FalconMedia\Core\ViewModel\StoreInfo;
use Magento\Framework\Escaper;

$imageUrl   = $block->getChildHtml('image');
$width      = str_replace('/12', '', $block->getChildHtml('width'));
?>

<section class="footer__logo col-xs-4 flex items-center col-md-<?= $escaper->escapeHtml($width); ?> mb-l">
    <a class="footer__logo--link" href="/" aria-label="Home page link">
        <img class="image footer__logo--image lazyload" src="data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw=="
             data-src="<?= $escaper->escapeUrl($imageUrl); ?>"
             loading="lazy"
             width="213"
             height="83"
        />
    </a>
</section>
