<?php declare(strict_types=1);

/**
 * @var $block Template
 * @var $escaper Escaper
 */

use Elgentos\PrismicIO\Block\Template;
use Magento\Framework\Escaper;

$heading     = $escaper->escapeHtml($block->getChildHtml('heading'));
$width       = str_replace('/12', '', $block->getChildHtml('width'));
$background  = $escaper->escapeHtml($block->getChildHtml('background'));

?>

<section class="header__store col-xs-12 col-md-<?= $width; ?> background-color--<?= $background; ?> mb-l mr-0">
    <?=/* @noEscape */ $block->getChildHtml('items') ?>
</section>
