<?php declare(strict_types=1);

/**
 * @var $block Template
 * @var $escaper Escaper
 */

use Elgentos\PrismicIO\Block\Template;
use Magento\Framework\Escaper;

$dummy        = $block->getContext();
$heading      = $escaper->escapeHtml($block->getChildHtml('heading'));
$width        = str_replace('/12', '', $block->getChildHtml('width'));
$sliderId     = $escaper->escapeHtml(uniqid());
$itemsDesktop = $escaper->escapeHtml($block->getChildHtml('desktop'));
$itemsTablet  = $escaper->escapeHtml($block->getChildHtml('tablet'));
$itemsMobile  = $escaper->escapeHtml($block->getChildHtml('mobile'));

//var_dump($block->getContext());die; // show only output
//highlight_string(print_r($dummy, true)); // show inline on page
?>

<section class="footer__brands brands span-item-12 lg:span-item-<?= $width; ?> mb-4">
    <div class="container">
        <?php if ($heading) : ?>
        <h3 class="font-size-l pb-1 text-center font-weight-600"><?= $heading ?></h3>
        <?php endif; ?>
        <div class="sliderhtml-<?= $sliderId; ?>">
            <?=/* @noEscape */ $block->getChildHtml('items') ?>
        </div>
    </div>
</section>

<script>
    // <![CDATA[
    require([
        'jquery',
        'domReady',
        'slick',
    ], function ($) {
        $(".sliderhtml-<?= $sliderId; ?>").slick({
            dots: true,
            arrows: false,
            infinite: true,
            speed: 300,
            slidesToShow: <?= $itemsDesktop ?>,
            slidesToScroll: 1,
            responsive: [
                {
                    breakpoint: 1200,
                    settings: {
                        slidesToShow: <?= $itemsDesktop ?>,
                        slidesToScroll: 1
                    }
                },
                {
                    breakpoint: 769,
                    settings: {
                        slidesToShow: <?= $itemsTablet ?>,
                        slidesToScroll: 1
                    }
                },
                {
                    breakpoint: 540,
                    settings: {
                        slidesToShow: <?= $itemsMobile ?>,
                        slidesToScroll: 1
                    }
                }
            ]
        });
    });
    // ]]>
</script>
