<?php declare(strict_types=1);

/**
 * @var $block Template
 * @var $escaper Escaper
 */

use Elgentos\PrismicIO\Block\Template;
use Magento\Framework\Escaper;

$heading  = $escaper->escapeHtml($block->getChildHtml('heading'));
$menuId = $escaper->escapeHtml(uniqid());

?>
<li class="m-b--2">
    <h3 class="footer__title"><?= $heading ?></h3>
    <div class="dropdown-list__content md-m-0" id="dropdown-<?= $menuId; ?>" data-level="1" aria-hidden="false">
        <ul class="list">
            <?=/* @noEscape */  $block->getChildHtml('menu_items') ?>
        </ul>
    </div>
</li>
