<?php declare(strict_types=1);

/**
 * @var $escaper Escaper
 * @var $block Template
 */

use Elgentos\PrismicIO\Block\Template;
use Magento\Framework\Escaper;

?>

<div class="hero hero--secondary hero--category">
    <div class="hero__wrapper">
        <div class="hero__content">
            <h1 class="hero__text--heading--title">
                <?= $escaper->escapeHtml($block->getChildHtml('title')); ?>
            </h1>
            <p class="hero__text--heading--description">
                <?=/* @noEscape */ $block->getChildHtml('description'); ?>
            </p>
        </div>
        <div class="hero__image">
            <img class="image lazyload"
                 src="<?= $escaper->escapeUrl($block->getChildHtml('image')); ?>"
                 alt="<?= $escaper->escapeHtml($block->getChildHtml('title')); ?>" />
        </div>
    </div>
</div>
