<?php declare(strict_types=1);
use Elgentos\PrismicIO\Block\Template;
use Magento\Framework\Escaper;

/**
 * @var Template $block
 * @var Escaper $escaper
 */

$url      = $escaper->escapeUrl($block->getChildHtml('url'));
$imageSrc = $escaper->escapeUrl($block->getChildHtml('image'));
$imageAlt = $escaper->escapeUrl($block->getChildHtml('image_alt'));
?>

<div class="full-image">
    <a href="<?= $url; ?>">
        <div class="image">
            <img src="<?= $imageSrc; ?>"
                 alt="<?= $imageAlt; ?>"
                 class="lazy"
             />
        </div>
    </a>
</div>
