<?php declare(strict_types=1);

/**
 * @var $block Template
 * @var $escaper Escaper
 */

use Elgentos\PrismicIO\Block\Template;
use Magento\Framework\Escaper;

$context    = $block->getContext();

$bg         = $escaper->escapeHtml($block->getChildHtml('bgc'));
$hoverBg    = $escaper->escapeHtml($block->getChildHtml('hover_bgc'));
$color      = $escaper->escapeHtml($block->getChildHtml('color'));
$icon       = $escaper->escapeHtml($block->getChildHtml('icon'));
$iconSize   = $escaper->escapeHtml($block->getChildHtml('icon_size'));
$text       = $block->getChildHtml('text');
$link       = $escaper->escapeUrl($block->getChildHtml('link'));

?>

<a href="<?= $link ;?>"
   class="quick-cards__item width-full border-radius bg-<?= $bg ?> flex flex-col aspect-auto-1/1 justify-center items-center hover:bg-<?= $hoverBg ?>">
    <svg class="icon size-<?= $iconSize ?> fill-<?= $color ;?>" role="img">
        <use xlink:href="<?= $escaper->escapeUrl($block->getViewFileUrl('/images/icons-sprite.svg')); ?>#<?= $icon ?>"></use>
    </svg>
    <h4 class="color-<?= $color ;?>"><?= $text ;?></h4>
</a>
